/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Task3.ui;

import Task3.dbmanager.DepartmentDBManager;
import Task3.dbmanager.StudentDbManager;
import Task3.model.Department;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Task3.model.Student;

/**
 *
 * @author Govind Kumar
 */
public class StudentManagementSystemFrame extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public StudentManagementSystemFrame() {
        initComponents();
        fillDepartmentCombox();
        fillStudentTable();
        clearFields();
    }

    StudentDbManager studentDbManager = new StudentDbManager();
    DepartmentDBManager departmentDbManager = new DepartmentDBManager();
    Integer studentId = 0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    String columns[] = {"Id", "Roll Number", "Name", "Father Name", "Age", "Email", "Department"};
    DefaultTableModel studentDefaultTableModel;

    private void fillStudentTable() {
        studentDefaultTableModel = new DefaultTableModel(columns, 0);
        try {
            List<Task3.model.Student> students = studentDbManager.getAllStudents();
            for (Task3.model.Student student : students) {
                Object row[] = {student.getId(), student.getRollNumber(), student.getName(), student.getFatherName(),
                    student.getAge(), student.getEmail(), student.getDepartment().getName()};
                studentDefaultTableModel.addRow(row);
                studentTable.setModel(studentDefaultTableModel);
            }

            studentTable.getColumnModel().getColumn(0).setWidth(0);
            studentTable.getColumnModel().getColumn(0).setMinWidth(0);
            studentTable.getColumnModel().getColumn(0).setMaxWidth(0);

        } catch (SQLException ex) {
            Logger.getLogger(StudentManagementSystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void fillDepartmentCombox() {
        List<Department> departments = departmentDbManager.getAllDepartments();
        for (Department department : departments) {
            departmentCombox.addItem(department.getName());
        }
    }

    private Task3.model.Student getStudent() {

        Task3.model.Student student = new Task3.model.Student();
        try {
            String rollNumber = rollNumberTextLabel.getText();
            String name = nameTextLabel.getText();
            String fatherName = fatherNameTextLabel.getText();
            Integer age = Integer.parseInt(ageTextLabel.getValue().toString());
            String email = emailTextLabel.getText();
            String departmentName = departmentCombox.getSelectedItem().toString();

            Department department = departmentDbManager.getDepartmentByName(departmentName);
            
            student.setRollNumber(rollNumber);
            student.setName(name);
            student.setFatherName(fatherName);
            student.setAge(age);
            student.setEmail(email);
            student.setDepartment(department);

        } catch (SQLException ex) {
            Logger.getLogger(StudentManagementSystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        return student;

    }

    private void clearFields() {
        rollNumberTextLabel.setText("");
        nameTextLabel.setText("");
        fatherNameTextLabel.setText("");
        ageTextLabel.setValue(0);
        emailTextLabel.setText("");
        departmentCombox.setSelectedItem("");
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        studentLabel1 = new javax.swing.JLabel();
        rollNumberLabel1 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        fatherNameLabel1 = new javax.swing.JLabel();
        ageLabel1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        departmentNameLabel1 = new javax.swing.JLabel();
        rollNumberTextLabel1 = new javax.swing.JTextField();
        nameTextLabel1 = new javax.swing.JTextField();
        fatherNameTextLabel1 = new javax.swing.JTextField();
        ageTextLabel1 = new javax.swing.JSpinner();
        emailTextLabel1 = new javax.swing.JTextField();
        departmentCombox1 = new javax.swing.JComboBox<>();
        addButton1 = new javax.swing.JButton();
        updateButton1 = new javax.swing.JButton();
        deleteButton1 = new javax.swing.JButton();
        clearButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        studentLabel = new javax.swing.JLabel();
        rollNumberLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        fatherNameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        departmentNameLabel = new javax.swing.JLabel();
        rollNumberTextLabel = new javax.swing.JTextField();
        nameTextLabel = new javax.swing.JTextField();
        fatherNameTextLabel = new javax.swing.JTextField();
        ageTextLabel = new javax.swing.JSpinner();
        emailTextLabel = new javax.swing.JTextField();
        departmentCombox = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setLocation(new java.awt.Point(300, 200));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        studentLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        studentLabel1.setText("Student Management System");

        rollNumberLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rollNumberLabel1.setText("Roll Number");

        nameLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nameLabel1.setText("Name");

        fatherNameLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fatherNameLabel1.setText("Father Name");

        ageLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ageLabel1.setText("Age");

        emailLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        emailLabel1.setText("Email");

        departmentNameLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        departmentNameLabel1.setText("Department Name");

        rollNumberTextLabel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollNumberTextLabel1ActionPerformed(evt);
            }
        });

        departmentCombox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT DEPARTMENT--" }));

        addButton1.setBackground(new java.awt.Color(204, 204, 255));
        addButton1.setText("Add");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        updateButton1.setBackground(new java.awt.Color(204, 204, 255));
        updateButton1.setText("Update");
        updateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButton1ActionPerformed(evt);
            }
        });

        deleteButton1.setBackground(new java.awt.Color(204, 204, 255));
        deleteButton1.setText("Delete");
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });

        clearButton1.setBackground(new java.awt.Color(204, 204, 255));
        clearButton1.setText("Clear");
        clearButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton1ActionPerformed(evt);
            }
        });

        studentTable1.setBackground(new java.awt.Color(204, 153, 255));
        studentTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        studentTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(studentTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(updateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(deleteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(clearButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(fatherNameLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(fatherNameTextLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(ageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(ageTextLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rollNumberLabel1)
                                .addGap(30, 30, 30)
                                .addComponent(rollNumberTextLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(nameLabel1)
                                .addGap(115, 115, 115)
                                .addComponent(nameTextLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(studentLabel1)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(emailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(emailTextLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(departmentNameLabel1)))
                                .addGap(18, 18, 18)
                                .addComponent(departmentCombox1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(studentLabel1)
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rollNumberLabel1)
                    .addComponent(nameLabel1)
                    .addComponent(rollNumberTextLabel1)
                    .addComponent(nameTextLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fatherNameLabel1)
                    .addComponent(ageLabel1)
                    .addComponent(ageTextLabel1)
                    .addComponent(fatherNameTextLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailLabel1)
                    .addComponent(departmentNameLabel1)
                    .addComponent(emailTextLabel1)
                    .addComponent(departmentCombox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 150));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        studentLabel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        studentLabel.setText("Student Management System");

        rollNumberLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rollNumberLabel.setText("Roll Number");

        nameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nameLabel.setText("Name");

        fatherNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fatherNameLabel.setText("Father Name");

        ageLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ageLabel.setText("Age");

        emailLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        emailLabel.setText("Email");

        departmentNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        departmentNameLabel.setText("Department Name");

        rollNumberTextLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollNumberTextLabelActionPerformed(evt);
            }
        });

        departmentCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT DEPARTMENT--" }));

        addButton.setBackground(new java.awt.Color(204, 204, 255));
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(204, 204, 255));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(204, 204, 255));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(204, 204, 255));
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        studentTable.setBackground(new java.awt.Color(204, 153, 255));
        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        studentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fatherNameLabel)
                                .addGap(33, 33, 33)
                                .addComponent(fatherNameTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(ageTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rollNumberLabel)
                                .addGap(30, 30, 30)
                                .addComponent(rollNumberTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(nameLabel)
                                .addGap(115, 115, 115)
                                .addComponent(nameTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(studentLabel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(emailTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(departmentNameLabel)))
                                .addGap(18, 18, 18)
                                .addComponent(departmentCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(studentLabel)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rollNumberLabel)
                    .addComponent(nameLabel)
                    .addComponent(rollNumberTextLabel)
                    .addComponent(nameTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fatherNameLabel)
                    .addComponent(ageLabel)
                    .addComponent(ageTextLabel)
                    .addComponent(fatherNameTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailLabel)
                    .addComponent(departmentNameLabel)
                    .addComponent(emailTextLabel)
                    .addComponent(departmentCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollNumberTextLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollNumberTextLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollNumberTextLabelActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            // TODO add your handling code here:

            boolean success = studentDbManager.addStudent(getStudent());
            if (success) {
                JOptionPane.showMessageDialog(this, "Student Added Successfully...");
                fillStudentTable();
                clearFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentManagementSystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            // TODO add your handling code here:
            Student student = this.getStudent();

            student.setId(studentId);

            boolean success = studentDbManager.updateStudent(student);

            if (success) {
                JOptionPane.showMessageDialog(this, "Student Updated Successfully...");
                fillStudentTable();
                clearFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentManagementSystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            // TODO add your handling code here:

            boolean success = studentDbManager.deleteStudent(studentId);

            if (success) {
                JOptionPane.showMessageDialog(this, "Student Deleted Successfully...");
                fillStudentTable();
                clearFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentManagementSystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void studentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTableMouseClicked
        try {
            // TODO add your handling code here:

            studentId = Integer.parseInt(studentTable.getValueAt(studentTable.getSelectedRow(), 0).toString());
            Student student = studentDbManager.getStudentById(studentId);
            rollNumberTextLabel.setText(student.getRollNumber());
            nameTextLabel.setText(student.getName());
            fatherNameTextLabel.setText(student.getFatherName());
            ageTextLabel.setValue(student.getAge());
            emailTextLabel.setText(student.getEmail());
            Department department = departmentDbManager.getDepartmentByName(student.getDepartment().getName());
            departmentCombox.setSelectedItem(department.getName());

        } catch (SQLException ex) {
            Logger.getLogger(StudentManagementSystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_studentTableMouseClicked

    private void rollNumberTextLabel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollNumberTextLabel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollNumberTextLabel1ActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButton1ActionPerformed

    private void updateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButton1ActionPerformed

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButton1ActionPerformed

    private void clearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearButton1ActionPerformed

    private void studentTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_studentTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManagementSystemFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel ageLabel1;
    private javax.swing.JSpinner ageTextLabel;
    private javax.swing.JSpinner ageTextLabel1;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton clearButton1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JComboBox<String> departmentCombox;
    private javax.swing.JComboBox<String> departmentCombox1;
    private javax.swing.JLabel departmentNameLabel;
    private javax.swing.JLabel departmentNameLabel1;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JTextField emailTextLabel;
    private javax.swing.JTextField emailTextLabel1;
    private javax.swing.JLabel fatherNameLabel;
    private javax.swing.JLabel fatherNameLabel1;
    private javax.swing.JTextField fatherNameTextLabel;
    private javax.swing.JTextField fatherNameTextLabel1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JTextField nameTextLabel;
    private javax.swing.JTextField nameTextLabel1;
    private javax.swing.JLabel rollNumberLabel;
    private javax.swing.JLabel rollNumberLabel1;
    private javax.swing.JTextField rollNumberTextLabel;
    private javax.swing.JTextField rollNumberTextLabel1;
    private javax.swing.JLabel studentLabel;
    private javax.swing.JLabel studentLabel1;
    private javax.swing.JTable studentTable;
    private javax.swing.JTable studentTable1;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updateButton1;
    // End of variables declaration//GEN-END:variables
}
